### ISSUE TITLE
[Feat] Prototype Contriutor Profile Tab > Profile Detail View

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#10]
### 📝 작업 목적

프로토타입 / Prototype Contributor Profile Tab 내에서 보여질 Profile Detail View 를 구현.

---

### 🛠️ Tasks

* [x] 공통뷰로 묶인 부분 (프로필 사진 및 기본 정보들) 구현
* [x] Follow 버튼 구현 -> 누르면 Unfollow 로 label 변경되도록
* [x] Knock 버튼 구현 -> 누르면 모달창 뜨도록
