### ISSUE TITLE
[Feat] GitHub REST API를 통한 네트워킹 구현

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#100]
### 📝 작업 목적

GitHub REST API를 통해 네트워킹하는 기능을 구현합니다.

---

### 🛠️ Tasks

* [x] API의 각 기능에 해당하는 Endpoint를 관리하는 구조체 생성
* [x] API Provider 구현 및 네트워킹 클래스 추상화 작업
* [x] ~~MockURLSession으로 테스트 가능하도록 구현~~
    - 개발 일정상의 이유로 추후 구현하도록 연기

### References
- [Swift clip: Managing URLs and endpoints](https://swiftbysundell.com/clips/4/)
- [테스트코드 멘토링](https://fern-melon-6e6.notion.site/_2301_copy-a311d0879d994d0e8d4c5e43c8303ee0#5c9c77b51371489ab0d646b4a8a34320)
- [iOS Networking and Testing](https://techblog.woowahan.com/2704/)
