### ISSUE TITLE
[Fix] Chat Room View UX 피드백 내용 반영

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#108]
### 📝 작업 목적
- UX 피드백에서 확인된 수정사항을 Chat Room View에 반영합니다.

---

### 🛠️ Tasks
* [x] Penpal -> Chat으로 레이블 수정
* [x] Async Image 로딩에 대한 앱 기본 프로필 이미지 세팅
* [x] 채팅방 상단 프로필 파트 컴포넌트화 및 재활용 배치

### Next TODO
- 채팅방 개별 설정 AppStorage 연결
- 프로필 이미지는 이후에 Github API에서 이미지 받아오기, 이미지 캐시 적용 등으로 크게 달라질 수 있음
- ViewModel 패치 코드 async로 리팩토링
- action 로직 private func로 분리
- 기존 View Components -> 디자인 시스템 Components로 리팩토링
- 채팅방 InfoView 구현
