### ISSUE TITLE
[Feat] Prototype MainPenpalView > MyKnockBox View

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#11]
### 📝 작업 목적

프로토타입 MainPenpalView의 MyKnockBox View를 구현합니다.
---

### 🛠️ Tasks

* [x] **MyKnockBox View**
  * [x] Knock한 유저의 정보와 시간에 대한 Cell 작업
  * [x] 각 Knock의 상태(대기 중인 노크, 응답한 노크, 거부한 노크)에 대한 이벤트 처리
    * [x] 대기 중인 노크
    * [x] 응답한 노크
    * [x] 거부한 노크
