### ISSUE TITLE
[Feat] ChatUserRecommendationSection 페이지네이션으로 수정

### ISSUE THREAD

**Issue by lianne-b** [APPSCHOOL1-REPO/finalproject-gitspace#110]
### 📝 작업 목적

ScrollView로 되어있던 ChatUserRecommendationSection를 페이지네이션으로 처리합니다.

---

### 🛠️ Tasks

* [x] TabView로 horizontal paging 처리 (카드 개수 3개로 제한)
* [x] 우측 끝에 다음 카드가 걸쳐지도록 구현
* [x] 기타 수정 사항: 팔로워, 레포 카운트 숫자 처리 (천 단위 넘어가면 k 붙여주고, width 값 고정)
* [x] 텍스트 디자인 시스템, gs색상 적용
