### ISSUE TITLE
[BugFix] ChatViewModel의 Fetch함수를 Completion -> async 로 변환

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#112]
**Describe the bug**
SkeletionUI를 사용하고 싶으나 패치 타이밍을 측정할 수 없음. -> 이러한 이유로 async 로 포팅 결정

**task**
* [x] fetch 함수를 Compleition에서 async로 변경
* [x] fetch 함수를 codable 방식으로 변경
* [x] targetName 연산프로퍼티를 viewModel에 published 변수로 옮기기
* [x] Chat model에서 tuple 분리
* [x] Skeleton UI에 대한 데이터 패치 타이밍 확인

With. Taeyoung
