### ISSUE TITLE
[Feat] MainProfileView > ProfileSettingView, AccounfManageView

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#12]
### 📝 작업 목적

로그인 된 본인의 프로필 뷰. 기본 정보들을 확인하고 본인의 깃헙 혹은 깃랩 계정관리를 할 수 있게 하는 페이지.
---

### 🛠️ Tasks

* MainProfileView
   * [x] 툴바 생성 (톱니바퀴 버튼)
   * [x] 프로필 뷰 (재사용)
   * [x] 툴바의 톱니바퀴 버튼 눌렀을 때 나오는 View 만들어서(ProfileSettingView) Navigation View 연결

* ProfileSttingView
   * [x] 설정에 들어갈 항목들 리스트화 해서 넣기 -> 프로토타입 종료

* AccountManageView
   * [x] Edit Mode 설정. -> (-) 표시 말고 Log out 등의 라벨로 변경해서 구현. -> 프로토타입 종료
