### ISSUE TITLE
[Fix] StarredView의 메뉴 레이블 변경 및 디자인시스템 적용

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#121]
### 📝 작업 목적

StarredView의 메뉴 레이블을 penpal에서 chat으로 변경합니다.
StarredView에서 사용되는 Text와 search field에 디자인시스템 적용합니다.

---

### 🛠️ Tasks

* [x] Menu의 Penpal 레이블 수정(Chat으로 변경)
* [x] Menu에 unstar 추가
* [x] Design System 적용 (Text, SearchField)
