### ISSUE TITLE
[Feat] MainKnockView > KnockControlView

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#124]
### 📝 작업 목적

1. 노크 컨트롤 화면을 구성합니다.

---

### 🛠️ Tasks

* [x] 노크를 보낼 수 있는 사람 설정
* [x] 노크 관련 설정
    * [x] 노크 알람을 받을지 말지
    * [x] 노크 수신거부
