### ISSUE TITLE
[Feat] AddTagSheetView의 TextField에 중복을 알려주는 애니메이션을 추가합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#130]
### 📝 작업 목적

AddTagSheetView에서 사용자 정의 태그를 추가할 때 중복 태그인 경우 사용자에게 알려주는 액션이 없습니다.
이를 TextField 애니메이션을 사용하여 중복 태그임을 알려주도록 합니다.
(TextField 양 옆으로 움직임 + TextField 하단에 '중복태그입니다' 메세지)

---

### 🛠️ Tasks

* [ ] AddTagSheetView 중복 태그일 때 감지하기 
* [ ] TextField의 부들부들 애니메이션 구현
* [ ] 중복 태그임을 알려주는 경고 메세지 TextField 아래에 출력
