### ISSUE TITLE
[Feat] Chat Collection Listener 도입

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#132]
### 📝 작업 목적
Chat Collection의 Listener 모듈을 세팅하고 MainChatView에 연결합니다.

---

### 🛠️ Tasks

* [x] ViewModel에 Chat Collection Listener 모듈 추가
* [x] Listener 작동 테스트
* [x] MainChatView 연결
* [x] Chat Documents 테스트 데이터 추가 후 작동 검증
* [x] View 진입 시 반복 패치에 대한 최적화
* [x] targetUserName 저장 방식 자료구조 변경

### 작업자
- 원태영 @wontaeyoung
- 정예슬 @yeseul321
