### ISSUE TITLE
[Feat] FCM 데이터 전송 및 노티 알람 탭 반응 후 랜딩 페이지 구현

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#134]
### 📝 작업 목적

1. FCM 데이터 전송 구현
2. FCM Push Notification을 탭 했을 때 뷰 네비게이션 구현

---

### 🛠️ Tasks

* [x] FCM 데이터 전송 구현 @ValseLee @lianne-b 
    * [x] Firebase ServerAPI로 어플리케이션 정보 보내는 로직 구현
    * [x] 실 기기 테스트
* [x] FCM Push Notification을 탭 했을 때 뷰 네비게이션 구현
    * [x] 노크 뷰 redirect
    * [x] 채팅 뷰 redirect
* [x] DeepLink 구현 @guguhanogu 

---
## Contributors
@ValseLee 
@lianne-b 
@guguhanogu
