### ISSUE TITLE
[Feat] Firebase Auth로 GitHub OAuth 로그인을 구현합니다. 

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#144]
### 📝 작업 목적

Firebase Authenticate의 OAuth 제공업체 중 하나인 GitHub로 GitHub OAuth를 구현합니다.

---

### 🛠️ Tasks

* [x] GitHub Application 등록을 위한 GitSpace의 Google, Github 계정 만들기
* [x] Google Authenticate에서 Github 설정하기
* [x] Xcode Project에 URL 스키마 추가하기
* [x] 로그인 뷰 생성하기
   * GitSpace Logo
   * GitHub Signin Button
* [x] InitialView 생성하기
   * 로그인 유무에 따라서 SigninView와 ContentView로 분기처리
* [x] GithubAuthenticate 클래스 완성하기
   * signin
   * signout
   * withdrawal
   * ~~validation~~
