### ISSUE TITLE
[Fix] MainKnockView, KnockSettingView > Search, Knock History 관리 수정 작업

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#145]
### 📝 작업 목적

1. 230208 피드백 관련 수정사항을 진행합니다. 태스크 참고.

---

### 🛠️ Tasks

* [x] Section Header에서 각 케이스에 대한 총 갯수 보여주기
    * [x] #154 
* [x] 검색 화면에서 cancel 버튼 구현
* [x] KnockSettingView > 30일 후 자동 삭제 예정인 거 명시해주기
