### ISSUE TITLE
[Feat] 인증된 사용자의 GitHub Starred Repository를 호출합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#153]
### 📝 작업 목적

StarredView에서 사용되는 사용자의 GitHub Starred Repository를 받아옵니다.
GitHub REST API로 호출하고 응답으로 받은 리스트를 화면에 출력합니다.

---

### 🛠️ Tasks

* [x] GitHub REST API에서 GitHub Starred Repository를 받아오는 API 확인
* [x] Repository 구조체 생성
* [x] RepositoryManager 클래스 생성
* [x] Request Starred Repositories 메서드 구현
* ~~LazyVStack으로 화면에 출력하기~~ (이슈로 분리)
   * 무한 스크롤
