### ISSUE TITLE
[Feat] MainKnockView > Code Refactoring with Modeling Knock networking

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#154]
### 📝 작업 목적

1. Knock 모델링을 진행하고 Firebase CRUD를 구현합니다.
2. KnockID 로 뷰를 그릴 수 있도록 코드를 리팩토링 합니다.
---

### 🛠️ Tasks

* [ ] Knock CRUD 모델링
    * [ ] 열거형 추상화
    * [ ] Delete는 30일 기준으로 자동삭제 or 유저 선택으로 삭제
* [x] Code Refactoring
    * [x] 꼬여있는 조건들 풀어서 열거형으로 정리
    * [x] 각 반복 셀마다 KnockID로 뷰 구성하도록 fetch해서 그리기
