### ISSUE TITLE
[Feat] 네트워크 기반 코드 추가

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#164]
### 📝 작업 목적

GitHub REST API사용을 위한 네트워크 기반 코드를 작성합니다. ^,,^ 

---

### 🛠️ Tasks

* [x] 에러 케이스별 열거형 추가
* [x] 기능별 Endpoint를 관리하기 위한 열거형 추가\
* [x] http request method별 열거형을 추가
* [x] data request를 위한 프로토콜 선언 및 함수 구현
