### ISSUE TITLE
[Fix] Chat 관련 모델링 변경 작업

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#169]
### 📝 작업 목적
Chat 관련 모델링 변경 회의 결과를 Chat 모델과 Firestore DB에 반영합니다.

---

### 🛠️ Tasks

* [x] Chat 구조체 프로퍼티 수정
* [x] Message 구조체 프로퍼티 수정
* [x] Firebase DB 필드명 수정
* [x] ViewModel, View 기존 프로퍼티 내용에 변경사항 반영

### 작업자
- 원태영 @wontaeyoung 
- 정예슬 @yeseul321
