### ISSUE TITLE
[Feat] 메세지 삭제 처리에 대한 lastContent 업데이트, 자신의 메세지에 대해서만 컨텍스트 가능하도록 조건 추가

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#171]
### 📝 작업 목적
- 채팅 메세지 버블 삭제 시 해당 메세지가 채팅방의 마지막 메세지인 경우, Chat 모델의 마지막 메세지를 바로 위 메세지의 내용으로 업데이트 하는 로직이 필요하여 구현합니다.
- 메세지 삭제 동작을 자신의 메세지에 대해서만 가능하도록 조건 로직을 추가합니다.

---

### 🛠️ Tasks

* [x] 메세지 삭제 컨텍스트 연결
* [ ] 메세지 버블의 작성자에 따라 삭제 처리 분기 추가
* [x] 메세지 삭제 시 해당 메세지를 로컬 배열에서 찾아서 삭제하는 로직 추가
* [x] 삭제 메세지가 배열의 마지막인 경우, Chat의 lastContent를 직전 메세지로 업데이트
* [x] Listener로 상대방 화면 실시간 적용 테스트

---

### Memo
카카오톡의 삭제 분기
1. 내 로컬에서만 삭제 가능한 경우 (이 케이스는 메세지 버블 자체가 삭제)
- 상대방의 메세지인 경우
- 내 메세지이지만 상대방이 읽은 경우

2. 양 쪽 모두 삭제 가능한 경우 (이 케이스는 '삭제된 메세지입니다.' 라는 문구로 버블이 남아있음)
- 내 메세지이지만 상대방이 읽지 않았고 5분이 경과하지 않은 경우
