### ISSUE TITLE
[Feat] 새로운 메시지 읽음/안읽음 처리 기능 구현

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#176]
### 📝 작업 목적

chatList에서 안읽은 메시지 갯수를 인식하고 그걸 화면에 띄워주는 기능을 구현합니다.

---

### 🛠️ Tasks

* [x] data structure에 안읽은 메시지 갯수를 넣을 필드 생성 + 모델에 추가
* [x] 상대방이 addMessage를 할 때마다 나의 안읽은 메시지 수 +1 
* [x] 받는 사람이 리스트를 보고 있을 때 -> 챗 리스너가 받는 사람의 로컬에서 안읽은 메시지 갯수 +1
* [x] 이후 받는 사람이 채팅방에 들어가면 갯수 0으로 초기화
* [x] 수신자와 발신자 모두 채팅방에 들어가있는 경우 -> 받는 사람의 채팅방 메시지 리스너 added에 갯수 0으로 초기화
