### ISSUE TITLE
[Fix] Chat, Message 파트에서 fix가 필요한 로직을 리팩토링합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#191]
### 📝 작업 목적
Chat과 Message의 make 메서드, 로그인 User의 ID를 임시 로그인 ID에서 실제 유저 객체 ID 참조로 리팩토링합니다.

---

### 🛠️ Tasks

* [x] 메세지 버블 컨텍스트 메뉴에 대한 사용자별 분기처리
* [x] Delete Message에 대해 unreadMessageCount -= 1 로직 추가
* [x] 메세지 컨텍스트 터치 범위를 가로 범위 전체에서 버블로 변경
* [x] makeMessage, makeChat 케이스 추상화
* [x] 마지막 메세지가 아닌 UnreadMessage가 삭제 시 count에서 감소되지 않는 현상 수정
* [x] Chat 관련 코드 임시 로그인 userID -> 실제 유저 객체 참조로 리팩토링
* [x] unreadMessageCount를 updateChat 필드에 추가
* [x] ChatRoomView 진입 시, 안 읽은 메세지를 0으로 초기화하는 로직 추가
* [x] ChatRoomView 안에서 메세지를 받을 때, 안 읽은 메세지를 증가시키지 않는 로직 추가
