### ISSUE TITLE
[Feat] Push Notification Connect2

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#213]
### 📝 작업 목적

1. Push Notification 을 노크 뷰에 배치합니다.

---

### 🛠️ Tasks

* [x] 노크 보내며 Push Notification 발신
* [x] 노크 상태에 따라 Push Notification 발신
    * [ ] UserInfo 관련 Feat 업데이트 후 Push notification이 발신되지 않는 이유 트래킹 필요
