### ISSUE TITLE
[Fix] AddTagSheetView의 Bug를 수정합니다. (title, textfield, enter)

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#215]
### 📝 작업 목적

AddTagSheetView에 있는 자잘한 기능을 수정합니다.

---

### 🛠️ Tasks

* [x] AddTagSheetView Title 수정
   * 현재 "Knock Knock"으로 제목이 달려있다.
   * 노크뷰가 아니라 사용자 정의 태그를 추가하는 뷰이기 때문에 다른 Title이 필요하다.
   * "Add Custom Tags"로 수정한다.
* [x] AddTagSheetView 태그 추가 후에 Textfield 초기화
* [x] AddTagSheetView 에서 엔터누르면 추가되도록 해야함
