### ISSUE TITLE
[Feat] TextEditor 텍스트 입력에 따른 자동 줄바꿈 구현하기

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#222]
### 📝 작업 목적
TextEditor의 높이를 개행문자로 인식하기 때문에, 텍스트 입력이 줄을 넘어가면서 발생하는 줄바꿈을 높이에 반영하지 못하는 문제를 해결하기
---

### 🛠️ Tasks

* [x] 입력된 텍스트의 가로 사이즈 계산 방식 찾아보기
* [x] 개행문자가 아닌 줄바꿈을 인식할 수 있는 값 찾아보기
* [x] 텍스트 입력으로 인한 자동 줄바꿈을 TextEditor 높이에 반영하는 로직 추가하기
