### ISSUE TITLE
[BugFix] Chat Room View 텍스트 메세지 전송 버튼 연속 탭 가능 문제 해결

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#223]
## 문제 현상
메세지 전송 버튼은 입력 텍스트가 빈 문자열이 아닐 때만 사용이 가능하지만, 전송 버튼의 액션 로직이 약 0.5초의 시간을 소요한 뒤 로직이 완료되어 텍스트 필드가 빈 문자열이 되기 전에 연속으로 탭할 수 있는 현상이 발생합니다.

## 예상 해결 방안
- 액션 버튼의 로직에 사용할 문자열을 temp 값에 보관하고 텍스트필드는 바로 빈 문자열을 할당하여 전송 버튼 탭이 불가하도록 한다.
- Bool 타입 변수를 생성하고, 버튼 탭 시 즉시 값을 토글하여 버튼을 disabled 한 뒤, 액션 로직이 종료되면 다시 toggle 한다.

## Task
* [x] 메세지 입력 필드의 내용을 임시 저장하기 위한 tempContent 추가
* [x] Chat, Message make 메서드에 업데이트를 위한 currentContent 파라미터 추가
* [x] 메세지 전송 로직 수행 전에 contentField를 초기화하여 버튼이 disabled 되도록 수정
