### ISSUE TITLE
[Feat] Chat Room View 입장 시 ScrollView 작동 로직 구현하기

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#224]
### 📝 작업 목적
- 채팅방 진입 시 읽지 않은 메세지의 첫 번째 위치부터 스크롤이 시작하도록 합니다.
- 채팅 메세지는 안 읽은 메세지 + 최근 메세지의 30개까지만 패치하고, 스크롤이 첫 메세지의 위치에 도달했을 때 이전 30개를 추가로 호출합니다.
- 채팅방 뷰에서 메세지가 추가되는 상황에 따라 ScrollView가 작동하는 로직을 구현합니다.

---

### 상황별 스크롤 동작
1. 내가 메세지 생성 -> 항상 최하단으로 이동
2. 상대가 메세지 생성 + 내가 채팅방 최하단 -> 추가된 메세지가 포함된 최하단으로 이동
3. 상대가 메세지 생성 + 내가 채팅방 중간 -> 하단 팝업 메세지, 탭하면 최하단으로 이동

### 🛠️ Tasks

* [x] 안 읽은 메세지 위치 계산 로직 구현
* [x] 채팅방 진입 시 안 읽은 메세지 위치부터 스크롤 작동
* [x] 안 읽은 메세지가 없는 케이스일 때, 최하단으로 스크롤 작동

### Memo
- 채팅방 최하단에서 스크롤이 시작해도 실제로는 첫 메세지 셀이 onAppear 된 후에 내려가는 방식이기 때문에 index onAppear 방식으로는 첫 메세지가 나타난 시점을 잡을 수 없음
