### ISSUE TITLE
[Feat] GuideCenter의 콘텐츠를 영문화 합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#225]
### 📝 작업 목적
GuideCenter의 콘텐츠를 영문화 합니다.

---

### 🛠️ Tasks

* [x] GuideCenter 영문화
* [x] Star Guide  영문화
* [x] Tag Guide 영문화
* [x] Activity Guide 영문화
* [x] Knock Guide 영문화
* [x] Chat Guide 영문화
* [ ] ~Block Guide 영문화~
* [ ] ~Report Guide 영문화~
