### ISSUE TITLE
[HotFix] RepositoryDetailView 의 화면 구조 변경

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#235]
### 📝 작업 목적

RepositoryDetailView의 컴포넌트들의 사이즈를 조정하고 재배치합니다.

---

### 🛠️ Tasks

* [ ] My Tags 라벨링 변경
* [ ] My Tag 위치변경
* [ ] 태그 디자인시스템 변경
* [ ] knock knock 버튼의 다크모드시 디자인시스템 변경
