### ISSUE TITLE
[Docs] 디자인 시스템 추상화 코드 기술연구

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#24]
### 📌 Documents 

- 디자인 시스템 추상화 코드를 구현하기 위한 기술연구를 진행합니다.

---

### 🛠️ Tasks

(레퍼런스는 RBG 채널의 코드 이미지로 대체합니다!)

* [x] 뷰 빌더와 열거형으로 뷰 케이스 분리 시도
* [x] 기본 뷰 컴포넌트 API를 확장하여 `GSView` 타입 정의
* [x] `extension Color` -> 색상 코드 적용
* [x] 뷰 컴포넌트 작업 분배 및 팀 코드 컨벤션 정립
* [x] 예시 코드 작성
* [x] 구현 예제와 추상화 요령 소개
