### ISSUE TITLE
[Feat] GithubUserInfo와 FirestoreUserInfo 통합 작업

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#245]
### 📝 작업 목적
GithubUserInfo 모델을 Firestore UserInfo 모델에 의존하는 형태로 통합합니다.

---

### 🛠️ Tasks

* [x] Firestore UserInfo 구조체에 GithubUser 프로퍼티 추가
* [x] Github 로그인 로직에서 서버와 API 중 상이한 정보에 대한 업데이트 기능 구현
* [x] Firestore 기존 유저정보 문서를 신규 유저정보 문서로 변경
* [ ] GithubUser와 FirestoreUser 병합으로 인한 Fix 예시 Chat에 적용
