### ISSUE TITLE
[Refactor] 변경된 UserInfo를 활용하여 Chat의 데이터 의존 구조를 변경합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#247]
### 📝 작업 목적
- UserInfo에서 GithubUser 필드에 접근할 수 있게 변경되어, Chat의 불필요한 메서드를 제거하고 데이터 의존 구조를 통일성 있게 변경합니다.

---

### 🛠️ Tasks

* [x] ChatViewModel에서 targetUserDict를 ChatID : targetUserInfo 구조의 딕셔너리로 변경
* [x] Github User와 FB UserInfo가 필요한 View에서 targetUserDict를 활용하는 구조로 변경
* [x] 더미 데이터로 표시된 TopperProfileView에 실제 UserInfo 데이터 연결
