### ISSUE TITLE
[BugFix] 상대방이 읽은 메세지를 삭제할 때, 마지막 메세지를 Chat 모델에 업데이트 하지 않는 문제 수정

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#248]
### 📝 작업 목적
- 상대방이 읽은 메세지를 삭제할 때, 마지막 메세지를 Chat 모델에 업데이트 하지 않는 문제 수정

---

### 🛠️ Tasks

* [x] 상대방이 읽은 메세지 여부, 삭제 메세지가 마지막 메세지인지에 대한 모든 분기 추가
* [x] Chat 업데이트 시 변경이 필요한 필드만 수정하는 로직으로 변경 
* [x] 메세지 삭제에 대한 Chat 업데이트 로직에 설명 주석 추가 
* [x] 실시간 채팅 시뮬레이션을 통해 수정 적용 확인
