### ISSUE TITLE
[Docs] Google FireStore Collection Group Query 기술 연구

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#25]
### 📌 Documents 
FireStore의 Collection Group Query 기술에 대한 연구를 진행합니다

---

### 🛠️ Tasks
* [x] 프로젝트 Firebase 패키지 추가
* [x] FireStore DB 연결
* [x] Collection Group 활용 목적 DB 구조 설계
* [x] Collection Group 쿼리 실행 확인
* [x] Collection Group 기술 문서 작성

@yeseul321
