### ISSUE TITLE
[Fix] 앱 강제 종료 시, 안 읽은 메세지 갯수가 반영되지 않는 현상 수정

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#250]
### 문제점
- [사용자가 채팅방 화면에 들어온 상태 + 상대방이 메세지를 전송]
이 상황에서 채팅방을 뒤로가기로 나가지 않고 앱을 강제로 종료하는 경우 안 읽은 메세지 갯수가 0으로 초기화되지 않음

### 원인
- 채팅방을 들어오기 전에 발생한 안 읽은 메세지 갯수는 채팅방 입장 시점에서 0으로 초기화되지만, 채팅방에 들어온 후 추가로 발생한 메세지는 채팅방을 나가는 시점에 0으로 초기화하기 때문
- DisAppear는 앱이 강제로 종료되거나 백그라운드로 보내질 때는 로직이 수행되지 않음

### 📝 작업 방향
- As-Is : 안 읽은 메세지 갯수 초기화 로직이 ChatRoomView의 DisAppear에 의존
- To-Be : UIApplication에서 백그라운드로 앱이 이동되는 것을 감지하는 기능을 통해 강제 종료에도 대응하도록 수정
- To-Be-Final : Environment ScenePhase로 앱의 생명주기를 감지하여 로직을 수행하도록 구현

### Memo
~~최종적으로는 메세지가 사용자 화면에서 노출되었을 때 실제로 unreadCount가 변하는 로직으로 수정이 필요함~~
메세지 셀을 통해서 count하는 방법이 읽기/쓰기 관점에서 비효율적이라고 판단하여 Chat의 unreadCount를 업데이트하는 시점을 디테일하게 잡는 것으로 변경

---

### 🛠️ Tasks
**NotificationCenter의 옵저버 관련 코드가 백그라운드 이동 시 감지하지 못하는 문제가 있어서 다른 방법 적용 필요!**
* [x] NotificationCenter의 Observer 학습
* [x] UIApplication에서 백그라운드 진입 감지 관련 내용 학습
* [x] NotificationCenter Observer로 UIApplication의 didEnterBackgroundNotification 감지 옵저버 적용

```swift
final class BackgroundManager {
        static var isQuit: Bool = false
        
        /// 매니저의 프로퍼티 하나를 수정하는 메서드를 만든다
        /// onChange로 뷰에서 해당 프로퍼티를 감지해서 채팅방 이탈 시 수행되어야하는 로직을 수행한다.
        @objc static func toggleIsQuit() {
            print("objc 시작")
            isQuit.toggle()
            print("objc 종료")
        }
    }

---

// FIXME: 현재 기준으로 백그라운드 진입 시 해당 selector 메서드가 호출되지 않음. 직접 post 해도 호출되지 않는 부분까지 포함해서 수정 필요. By 태영
            NotificationCenter.default.addObserver(self,
                                                   selector: #selector(BackgroundManager.toggleIsQuit),
                                                   name: UIApplication.didEnterBackgroundNotification,
                                                   object: nil)

---

.task(id: BackgroundManager.isQuit) {
            print("백그라운드 시작")
            NotificationCenter.default.post(name: UIApplication.didEnterBackgroundNotification,
                                            object: nil)
            await clearUnreadMessageCount()
            print("백그라운드 종료")
        }
```
<br>

**SwiftUI의 Environment ScenePhase를 통해 앱의 생명주기에 접근해서 로직 수행**
* [x] ScenePhase Environment 프로퍼티 추가
* [x] scenePhase 변경을 감지해서 inActive 케이스일 때, 채팅방 이탈과 동일하게 clearUnreadMessageCount 메서드 호출 

### 작업자
- 원태영 @wontaeyoung 
- 정예슬 @yeseul321
