### ISSUE TITLE
[Docs] 깃허브, 깃랩, 애플 SSO 로그인 기술연구

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#26]
### 📌 Documents 

깃랩, 애플 SSO 로그인을 구현하기 위한 기술연구를 진행합니다.
더불어 깃허브 로그인도 같이 구현합니다.

---

### 🛠️ Tasks

* [x] SSO란 무엇인가?
* [x] 애플 로그인이 무조건 필수인가? 알아보기
* [x] 깃랩 SSO 로그인 연구
* [x] 애플 SSO 로그인 연구
* [x] 깃허브 로그인 코드 구현

---

### 👥 Contributors
@dahae0320 
@guguhanogu
