### ISSUE TITLE
[Feat] GitHub Auto Login을 구현합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#263]
### 📝 작업 목적

현재 GitHub Login이 구현되어 있으나, 앱을 다시 실행하면 로그인을 또 해줘야 하는 문제가 있습니다.
이미 로그인한 유저의 편의를 위해 로그인 상태(login status)를 유지하는 **GitHub 자동 로그인**을 구현합니다.

---

### 🛠️ Tasks
* [x] **보통의 Auto Login이 어떻게 이루어지는지 구글링하기**
   * Auto Login: 사용자가 직접 로그인하지 않고 시스템에서 필요한 로그인 과정을 수행하는 것
   * 웹의 경우에는 세션 사용
   * 앱에서는 AT를 기기에 저장해서 사용
   * Firebase Auth를 쓰는 경우, Authenticate status를 기억한다. 그래서 `currentUser`의 유무로 자동 로그인을 구현할 수 있다.
* [x] **Auto Login 분기 처리**
  * Firebase Auth의 `currentUser`가 nil인지 아닌지로 분기 처리
   * InitialView의 `onViewDidLoad`에 해당 로직 작성
* [x] **reauthenticate 메서드 구현**
  * `signin`(auth)이 아니라 `reauth`를 해줘야 자연스럽다.
  * `signin`(auth)를 해줘도 되지만, Firebase에서 제공하는 GitHub 로그인은 사파리뷰가 떠버린다. 그래서 자연스러운 자동 로그인이 불가능하다.
  * Firebase Provider라면 credential을 가져올 수 있다.
     * `GitHubProvider.credential(withAccessToken:)`
  * 이것으로 reauthentification에서 필요한 credential을 불러올 수 있다.
