### ISSUE TITLE
[Fix] Chat DB와 관련된 리터럴 값을 전역 상수로 활용하도록 변경합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#264]
### 📝 작업 목적
- Chat, Message, Field name과 같은 DB 경로 혹은 필드명 리터럴 값을 전역 상수로 교체합니다.

---

### 🛠️ Tasks
* [x] Constant 객체에 Chat, Message DB 컬렉션, 필드 전역상수 열거형 추가
* [x] ChatViewModel, MessageViewModel Firestore Path 코드에 전역상수 적용
* [x] 날짜 관련 연산프로퍼티 변수명 직관적으로 수정
