### ISSUE TITLE
[Docs] GitHub Markdown API를 활용한 README 렌더링 기술검증

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#27]
### 📌 Documents 

GitHub Markdown API를 사용하여 특정 레포지토리의 README.md를 가져오고, RepopsitoryDetailView에서 렌더링 하는 방법을 알아봅니다.

---

### 🛠️ Tasks

* [x] GitHub Markdown API Docs 확인
* [x] GitStar (MVP 프로젝트)에서 기존에 사용하던 방법 체크
* [x] Markdown을 SwiftUI에서 보여줄 수 있는 방법 서칭
