### ISSUE TITLE
[Fix] UserProfileView 버그 수정 및 추가 작업

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#271]
### 📝 작업 목적

UserProfileView의 버그를 수정하고 추가적인 작업을 진행합니다.

---

### 🛠️ Tasks

* [x] CurrentUserProfileView, TargetUserProfileView의 스크롤바 제거
* [x] TargetUserProfileView(특정 유저의 프로필)와 CurrentUserProfileView(사용자의 프로필) 디자인 통일 작업
* [x] TargetUserProfileView이 만약 자기자신의 프로필을 보여주고 있다면 Follow 및 Knock 버튼을 제거
* [x] 유저가 깃허브에서 설정한 이름이 없다면 깃허브 아이디만 보여주고, 유저가 깃허브에서 설정한 이름이 있다면 이름과 아이디 모두 보여주도록 수정
* [x] TargetUserProfileView에서 팔로우 / 팔로잉 버튼의 기능 동작하도록 구현
* [x] TargetUserProfileView에서 GitSpace 유저가 아니라면 팔로우 / 팔로잉 버튼만 보이도록 구현
* [x] TargetUserProfileView, CurrentUserProfileView에서 README를 불러올 수 없을 때 메시지를 띄우지 않고 이미지가 포함된 뷰를 보여주도록 수정
* [x] README 불러올 때 로딩 뷰 수정
