### ISSUE TITLE
[Fix] GitHub SignIn Auth 중 로딩 뷰 수정

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#281]
### 📝 작업 목적

GitHub SignIn 버튼 탭한 후 뜰 로티가 포함된 로딩뷰를 띄우고 내릴 타이밍 수정 및 자동로그인 기능과의 연결성 추가 할 예정입니다.

---

### 🛠️ Tasks

* [x] GitHub 로그인 웹뷰가 띄워진 후 로그인을 진행하지 않고 그냥 웹뷰 닫았을 때 무한 로딩이 되는 문제 발생
          -> 로그인 진행 상황에 따라 state case에 .pending을 추가하여 pending 상태일 때는 로딩뷰를 띄우도록 코드 수정.

* [x] InitialView에 .pending인 경우 LoadingProgressView를 띄워주도록 하였더니 colorScheme을 올바르게 읽어오지 못하는 현상 발생.
          -> 다혜님께 InitialView에 대해 물어본 후 colorScheme이 적용될 수 있는 방향으로 코드 수정. 
          
* [x] 자동로그인 진행 시 딜레이 발생하는데 이 타이밍에는 로티 로딩뷰가 안 뜨는 문제 발생
          -> 자동로그인 로직 이해 후 전체적으로 state case 수정하여 위와 같이 해결할 것.
