### ISSUE TITLE
[Fix] Utility의 loginUserID 전역 상수를 UserViewModel의 currentUser 사용으로 교체합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#282]
### 📝 작업 목적
현재 로그인 유저 ID를 활용하기 위해 임시로 사용하고 있는 Utility의 loginUserID를 폐기하고, 로그인 시 할당되는 UserViewModel의 currentUser를 사용합니다.

---

### 🛠️ Tasks

* [ ] 혼합되어 사용되는 UserViewModel의 user와 currentUser를 하나로 통합
* [ ] Utility의 loginUserID를 참조하고 있는 코드를 UserViewModel의 currentUser로 변경
* [ ] 각 View에서 정상적으로 userInfo를 받아오고 참조할 수 있는지 테스트
