### ISSUE TITLE
[Design] GSTextEditor 디자인 시스템의 색상 값을 변경합니다

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#287]
### 📝 작업 목적
- 디자인 컨펌 결과를 TextEditor 색상에 반영하고, ColorScheme 조건을 Asset의 Darkmode 색상으로 변경합니다

---

### 🛠️ Tasks

* [x] 돋보기 아이콘 색상 변경
* [x] TextEditor 백그라운드 색상 변경
* [x] ColorScheme 삼항 연산자 제거
