### ISSUE TITLE
[Docs] FireStore Listener 기술 연구

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#29]
### 📌 Documents 
FireStore의 Listener 기술에 대한 연구를 진행합니다

---

### 🛠️ Tasks
* [x] Listener 기본 개요 조사
* [x] Listener 기반코드 작성
* [x] Listener 작동 검증
* [x] Listener 작동 검증에 따른 Fetch 기반코드 수정
* [x] Listener 문서 작성

w. @yeseul321
