### ISSUE TITLE
[Feat] 노크 수락 시 채팅방을 생성하고 연결하는 기능을 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#293]
## 📝 작업 목적
-  노크 수락 시 채팅방을 생성하고 연결하는 기능 구현

---

## 🛠️ Tasks

* [x] 노크 수락 시점에 채팅방 생성 로직 호출
* [x] 탭 라우터를 Chat 탭으로 이동

### 원인과 히스토리
23.03.18
Listener에서 async 메서드를 await 호출할 수 없는 문제
1. Chat 탭을 한 번이라도 유저가 진입한 후에는 Request가 발동하지 않고 Listener에 의해서 추가되는 Chat을 감지하여 로컬에 추가함
2. 노크 수락 -> 채팅방 생성 -> Chat 탭으로 라우팅 하였을 때 Listener에 의한 로컬 Chat 리스트 반영이 되지 않는 현상 발견
3. 확인 결과 Chat에 해당하는 targetUserInfo가 존재해야 채팅방 셀을 그리는 로직으로 List가 구현되어 있었음
4. Request Chat 로직에는 Chat과 targetUserInfo를 모두 받아오는 로직이 있었지만 Listener의 Added 로직에는 targetUserInfo를 받아오는 로직이 누락되어 있었음
5. targetUserInfo를 받아오는 로직을 Listener Added 로직에 추가하였으나, Listener는 Async 구문을 지원하지 않아서 내부에서 await 키워드를 사용할 수 없음
6. Completion Handler를 Async 구문으로 감싸는 withContinuation 로직 시도
7. addSnapshotListener 메서드 특성상 리턴하는 listenerRegistration과 (snapshot, error)를 받아서 구현부를 작성하는 클로저가 동시에 존재하여 구현부에 async를 적용할 수 없었음
8. targetUserInfo를 받아오는 로직을 async 버전과 completion handler 버전 두 가지로 만들어서 시도
9. Completion Handler에서 시점 대기를 할 수 없는 문제로 필요한 데이터 response보다 로직이 더 빠르게 수행되어 실패

listener 사용 불가로 다음 내용들 트라이 예정
1. listener added 감지 시, ChatList를 한 번만 패치하기 위한 변수를 다시 false로 변경하여, 뷰 진입 시 다시 패치하도록 함
2. 뷰 전역에 onChange를 달 수 있는 방법을 찾아서, requestChats가 호출되도록 함

23.03.19
프로퍼티 감시자를 활용하여 addSnapshotListener handler에서는 변수를 변경하고, 감시자에서 비동기 로직을 처리하도록 구현하였으나, 이 과정에서 Completion Handler 클로저 내부에서 Task 블록을 사용하면 await 키워드를 사용할 수 있음을 알게되어 해당 방법으로 문제 해결

### Tasks
* [x] ~~UserViewModel의 requestAndReturnUser 메서드의 Completion Handler 버전 메서드 추가~~
* [x] ~~listenerAddChat 메서드의 async 키워드 제거~~
* [x] ~~listener added 블록에서 chat 패치 트리거 변수를 false로 변경하도록 변경~~
* [x] ~~Initial View 하단에 frame 값이 0인 투명 오브젝트를 두어서, 앱 전역에서 onChange를 감지하도록 추가~~
* [x] ~~isKnockAceepted 변수와 프로퍼티 감시자로 willSet 내부에서 비동기 로직 처리 구현~~
* [x] listener added 블록에 Task 블록 추가하여 비동기 로직 처리
