### ISSUE TITLE
[Fix] 전체 뷰 확인 및 다크모드 대응, 뷰 간 간격 및 패딩값 조정

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#295]
### 📝 작업 목적

전체적인 뷰에서 다크모드 대응이 안된 부분은 수정을 통해 다크모드를 대응하고 이외의 뷰 간의 간격이 안맞는 문제나 추가적으로 수정해야 할 부분을 예은님의 피드백을 통해 수정해나갈 예정입니다.

---

### 🛠️ Tasks

* [x] 전체 뷰 중 다크모드 대응 안된 곳 리스트업
* [x] 다크모드 대응 안된 곳 수정 (디자인 시스템 적용 및 디자인 시스템 자체를 수정)
* [x] 뷰 간 간격 및 패딩값 조정 (1차 수정)
* [x] 예은님 피드백
* [x] 예은님 피드백 후 수정 (2차 수정)
