### ISSUE TITLE
[Feat] KnockViewManager > checkIfKnockHasBeenSent 

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#298]
### 📝 작업 목적

1. 노크가 보내졌는지 확인하고 필터링하는 로직을 구현합니다.

---

### 🛠️ Tasks

* [x] knockStatus 필터링하여 결과 타입으로 리턴
* [x] 결과 타입의 KnockStateFilter에 beforeSent 케이스 추가 -> 노크가 보내지기 전 분기처리
    * [x] Accepted -> chat 라우팅
    * [x] Waiting, Declined -> KnockHistoryView 라우팅
    * [x] 보내진 적 없을 경우 -> SendKnockView 라우팅
    * [x] 이미 단 한 번이라도 노크가 보내진 적이 있을 경우 -> KnockHistoryView 라우팅
