### ISSUE TITLE
[Feat / Chore] SendKnockView | 최초 릴리즈 버전에 맞게 뷰를 수정합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#303]
### 최초 릴리즈 버전에 맞게 SendKnockView를 수정합니다.
1. ` View Profile ` NavigationLink를 해당 유저의 프로필로 이동할 수 있도록 연결합니다.
2. 구현하지 못한 기능들을 주석처리 또는 제거합니다.
    - TextEditor 섹션의 사진 / 코드 첨부 버튼 제거
    - `Offer` / `Question` 버튼 다크모드 대응

---

### 🛠️ Tasks

* [x] 1. `View Profile` NavigationLink 해당 유저의 프로필로 연결하기
* [x] 2. TextEditor 섹션의 사진 첨부 버튼 제거
* [x] 3. TextEditor 섹션의 코드 첨부 버튼 제거
* [x] 4. `Offer` 버튼 다크모드 대응
* [x] 5. `Question` 버튼 다크모드 대응
