### ISSUE TITLE
[Feat / Design] GSTextEditor에 공백 검사 로직을 추가합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#310]
### 📝 작업 목적
- 현재 GSTextEditor는 각 View에서 문자열이 비어있는 경우 전송을 할 수 없도록 처리되어있지만, 공백문자 혹은 개행문자가 입력되면 전송이 가능합니다.
- 정규식을 활용해 해당 케이스를 검사하고, 의도에 맞게 전송될 수 있도록 수정하는 메서드를 구현한 뒤, TextEditor를 사용하는 모든 View에서 별도로 구현하지 않도록 디자인 시스템으로 해당 로직을 이동합니다.

---

### 🛠️ Tasks

* [x] 공백 / 개행문자만 존재하는 케이스를 검사하는 정규식 패턴 구현
* [x] GSTextEditor 디자인 시스템으로 문자열 검사 로직 위치 변경
* [x] 메세지 전송 버튼을 디자인 시스템 내부로 이동
