### ISSUE TITLE
[Feat] 신규 개설된 채팅방을 유저가 인식할 수 있도록 New 라벨을 추가합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#322]
### 📝 작업 목적
노크 수락 후 개설된 채팅방이 유저에게 인지될 수 있도록 채팅방 리스트에서 New 라벨을 추가합니다.

---

### 🛠️ Tasks

* [ ] 신규 채팅을 구별하기 위한 로직 구현
* [ ] Firestore에 신규 채팅 구별용 프로퍼티 추가
* [ ] 구현된 로직으로 New 문구 라벨링 추가
