### ISSUE TITLE
[Bugfix] clearUnreadMessageCount 메서드 비정상 작동 수정

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#326]
### 📝 작업 목적
- 채팅방 진입 / 탈출 시점에 호출되는 clearUnreadMessageCount 메서드가 정상적으로 작동하지 않는 현상 수정
- 호출 확인을 위해 print 호출을 추가하면 정상적으로 작동되는 현상을 발견해서 Task가 추가됨에 따라 확보된 작업 시간이 비동기에 영향을 미치는지 확인 필요

---

### 🛠️ Tasks
* [x] 버그가 발생 원인 확인
* [x] 버그 로직 수정
* [x] 사용자 기기 두 개로 작동 테스트

### Additional Tasks
* [x] 채팅방 진입 시, 읽지 않은 메세지가 0개인 경우 clearUnreadMessageCount를 호출하지 않도록 조건 추가
* [x] 채팅방 퇴장 시, 추가로 생성된 메세지가 없으면 clearUnreadMessageCount를 호출하지 않도록 조건 추가

### Issue 기록
버그 발생 원인 확인 결과, 옵셔널 값인 userStore의 user가 존재하지 않는 경우 unreadMessageCount를 0으로 만들 대상 유저를 찾을 수 없기 때문에 로직이 수행되지 않아서 발생한 문제임을 확인.
userStore의 user는 앱 실행 시점에서 Request를 통해 할당하기 때문에, 상기한 시점에서 유저 정보가 nil인 경우는 존재할 수 없지만 발생하게 된 상황.
ViewModel의 Published 변수는 데이터 신뢰성이 높은 편은 아닌 것으로 확인되어, 로그인 시 유저 ID를 저장하여 활용하는 전역 상수 loginUserID를 통해서 로직을 수행하도록 변경하여 버그를 해결.
