### ISSUE TITLE
[Feat] TargetUser의 Following과 Followers List를 호출하는 함수를 구현합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#327]
### 📝 작업 목적
TargetUser의 Following과 Followers List를 호출하는 함수를 구현합니다.

---

### 🛠️ Tasks

* [ ] GitHubAPIEndpoint에 case 추가하기
* [ ] GitHubServiceProtocol에 함수 추가하기
* [ ] GitHubService에 함수 구현하기
* [ ] 함수 잘 작동하는 지 테스트하기
