### ISSUE TITLE
[Fix] StarredView에서 필요한 수정사항을 반영합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#339]
### 📝 작업 목적

StarredView에서 필요한 수정사항을 반영합니다. 
* v1.0.0 에서 사용하지 않는 기능 주석 처리
* unstar 기능 등록하기
* 한글로된 Label 영어로 수정하기

---

### 🛠️ Tasks

* [ ] StarredView의 ellipsis button 기능 주석처리
   * share, chat 주석처리
* [ ] StarredView의 ellipsis button의 unstar 기능 연결하기
* [ ] AddTagSheetView의 context menu Label 수정하기
  * `태그 삭제하기` -> `delete tag`
