### ISSUE TITLE
[Docs] FireStore Listener를 적용한 채팅 기능 데모

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#36]
### 📌 Documents 
작동 검증이 완료된 FireStore Listener를 적용하여, 채팅 데이터 CRUD 데모를 구현합니다.

---

### 🛠️ Tasks
* [x] 채팅 View 및 기능 기반코드 세팅
* [ ] AddListener 작동 시 기존 DB 문서를 New Document로 인식하는 현상에 대한 예외처리 구현
* [ ] Modified, Removed 타입에 대한 메세지 수정, 삭제 반영처리
* [ ] 채팅방 입장, 퇴장 시점에 Listener 작동 관리 연결
