### ISSUE TITLE
[Fix] 릴리즈 버전에 사용할 dev의 버그를 수정합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#360]
### 📝 작업 목적

---

### 🛠️ Tasks
* [x] TargetUserProfileView의 Knock 버튼에 sendKnockView 네비게이션 링크 연결
* [x] GSButton의 버튼 스타일을 GSNavigationLink와 동일하게 수정
* [x] ChatRoomView 툴바 버튼 삭제
* [x] ReceivedKnockView Block 버튼 삭제
* [x] SendKnockView의 KnockMessage 전송 버튼 연속 탭 가능한 문제 해결
* [x] SendKnockView의 TextEditor가 노크 메세지 전송 후 사라지도록 변경
* [x] ContributorListView currentUser 강제 언래핑 Fatal Error 해결
