### ISSUE TITLE
[HotFix] 릴리즈 버전의 dev 브랜치 버그를 수정합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#361]
### 📝 작업 목적

---

### 🛠️ Tasks

* [x] contributorListView githubID 옵셔널 로직 수정
* [x] 회원 탈퇴에 signOut과 UserDefault(AT)에 nil 할당하는 로직 추가
* [x] 자동 로그인 reAuth 로직에 Firestore User 정보를 업데이트하는 registerNewUser 호출 추가
* [ ] 회원 탈퇴 시, github 로그인 정보가 삭제되도록 수정
* [x] 로그인 뷰 하단에 이용 약관 네비게이션 추가

**Comment by wontaeyoung** [comment]
4번 Task github 로그인 정보 삭제 방법을 찾지 못해서 다음 issue에서 해결하기로 합의
