### ISSUE TITLE
[Docs] 신고 및 차단 기능 모델링

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#364]
### 📌 Documents 

신고와 차단 기능을 구현하기 위해 모델링을 진행합니다.

---

### 🛠️ Tasks

* [x] 전체 회의를 통한 신고 및 차단 기능 합의
* [x] 필요한 필드 정의
* [x] 신고 및 차단 모델링(피그잼)

#### Report
```swift
Struct Report {
   var id: String = UUID().uuidString
   var reason: String   
   var reporterID: String
   var targetUserID: String
   var date: Date
   var content: String = “${욕설메세지}”
   var type: String  // ex. 노크신고, 채팅신고, 유저신고 }
```
#### Block
```swift
UserInfo의 blockedUserIDs 배열로 관리한다.
```
