### ISSUE TITLE
[Feat] 신고 모델과 신고/차단 로직 추상화를 위한 프로토콜을 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#365]
### 📝 작업 목적
- 불쾌감을 주는 사용자, 컨텐츠를 신고하기 위한 모델을 추가합니다.
- 신고/차단에 대한 로직을 프로토콜로 구현하고 채택할 수 있도록 합니다.
- 차단 여부에 따라 뷰를 분기처리합니다.

---

### 🛠️ Tasks

* [x] 신고 모델 추가
* [x] 신고 프로토콜 구현
* [x] 차단 프로토콜 구현

### 주요 로직
- #366
