### ISSUE TITLE
[Feat] 채팅 메세지를 신고하는 기능을 추가합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#373]
### 📝 작업 목적
- 신고가 필요한 메세지에 대해, 신고할 수 있는 기능을 뷰에 구현합니다.

---

### 🛠️ Tasks

* [x] 상대 메세지 Cell에 ContextMenu 추가
* [x] 신고 대상 메세지 객체를 담을 reportedMessage 변수 추가
* [x] reportedMessage 옵저빙 로직 추가
