### ISSUE TITLE
[Feat] 채팅방에 차단 검사와 신고 sheet을 연결합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#388]
### 📝 작업 목적
- 채팅방 차단 분기 로직에 차단 검사 로직 연결
- Message Cell Context Menu 신고 버튼에 신고 sheet present 로직 연결

---

### 🛠️ Tasks

* [x] GSTextEditor에 차단 검사 메서드 호출 결과 전달
* [x] 신고 sheet present 바인딩 변수 추가
* [x] onChange에서 감지하기 위한 isReported 변수 추가
* [x] 신고 sheet present 로직 추가
* [x] 신고 sheet View 작성
