### ISSUE TITLE
[Fix] 회원 탈퇴한 유저의 Knock > Profile 속 Image modifier가 계속 작동하는 현상을 수정합니다.

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#391]
### 📝 작업 목적

1. 회원 탈퇴 유저에 대한 분기처리
    - 회원 탈퇴 이후, KnockMainView에서 Image가 계속 fetch 되고, 분기처리 되지 않는 현상 수정

---

### 🛠️ Tasks

* [x] 둘 중의 하나의 태스크를 진행합니다.
    * [x] loading 결과 유저가 없을 경우 placeholder로 image 수정합니다.
    * [x] 기본 image를 placeholder 이미지로 바꾸고 skeleton을 deprecate합니다.

**Comment by ValseLee** [comment]
1. loading 결과로 유저가 없을 때를 받아오기 위해서는 completionHandler를 활용해야 하는데... 모든 userInfo를 불러오는 곳에서 현재 async 처리가 되어 있음
2. 출시를 위해 우선 SkeletonUI를 deprecate

**Comment by ValseLee** [comment]
SkeletonUI를 request 결과에 따라 분기처리 완료
