### ISSUE TITLE
[Fix] 깃스페이스 유저가 아닌 경우 TargetUserProfileView에서 ellipsis가 보이지 않도록 수정합니다.

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#393]
### 📝 작업 목적

깃스페이스 유저가 아닌 경우 TargetUserProfileView에서 ellipsis가 보이지 않도록 수정합니다.
기존 깃스페이스 유저 확인 로직을 점검합니다.

---

### 🛠️ Tasks

* [x] 기존 깃스페이스 유저 확인 로직이 잘 작동하는지 확인
    * [x] TargetUserProfileView로 연결된 NavigationLink확인
* [x] 로직 수행 후 깃스페이스 유저가 아니거나, TargetUser == currentUser인 경우 Ellipsis를 제거
* [x] 이미 블락된 유저인 경우, Ellipsis에서 block 메뉴가 나타나지 않도록 처리
