### ISSUE TITLE
[Fix] Repository에 갓 생성한 태그를 바로 등록할 경우, 중복 선택되는 에러를 고칩니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#397]
### 📝 작업 목적

현재 특정 Repository에 원하는 태그를 등록할 수 있습니다.
이때 새로 생성한 태그를 바로 등록할 경우, 중복 선택되는 에러를 고칩니다.

> 바로 등록한다 == 태그 생성 후 다른 뷰로 나가지 않고 생성한 태그를 레포지토리에 바로 등록하는 경우

---

### 🛠️ Tasks

* [x] 에러 발생 시나리오 확인
   * Tag의 생성 시점과는 상관없이 발생합니다.
   * 시나리오
       1. RepositoryDetail에서 '+'버튼 눌러 AddTagSheetView로 이동
       2. AddTagSheetView에서 특정 Tag를 Selection 후 Done 버튼 탭
       3. AddTagSheetView dismiss
       4. RepositoryDetail Appear
       5. 다시 1번 - 4번 반복하면 RepositoryDetail의 My Tag에 같은 태그가 2번 들어간다.
* [x] 원인 파악하기(기록해서 PR에 적기)
* [x] BugFix
* [x] 버그가 작동되지 않는지 확인하기
