### ISSUE TITLE
[Feat] 앱 실행시, Current User의 Blocked Users를 불러오는 메서드를 구현하고 적용합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#398]
### 📝 작업 목적
앱 실행시, Current User의 Blocked Users를 불러오는 메서드를 구현하고 적용합니다.

현재 Current User의 Blocked Users를 확인하기 위해서는
`Settings`-> `Account`-> `Blocked users`에 진입해야 합니다.

`BlockedUsersListView`에 있는 `convertUserInfo` 메서드를
상위 뷰에서 실행시켜 앱이 실행될 때에 Current User의 Blocked Users를 불러오게 할 예정입니다.

---

### 🛠️ Tasks

* [x] 앱 실행 시 `convertUserInfo` 메서드 실행
* [x] 자동 로그인 시 `convertUserInfo` 메서드 실행
* [x] 버그 발생 유무 확인
