### ISSUE TITLE
[Chore] BlockedUsers Class의 위치를 변경하고, BlockedUserList에 값을 추가할 때 중복검사를 진행합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#412]
#### 1. BlockedUsers Class의 위치를 변경합니다.
- 기존 `Blockable.swift` 파일에 위치해 있던 `BlockedUsers` Class를 별도의 파일로 옮깁니다.

#### 2. BlockedUserList에 값을 추가할 때 중복검사를 진행합니다.
- 현재 차단한 유저를 다시 차단할 수는 없지만,
 만일을 위해 중복검사를 통해 중복된 값이 추가되지 않도록 합니다.

---

### 🛠️ Tasks

* [x] `BlockedUsers.swift` 파일 생성
* [x] `BlockedUsers` Class 위치 변경
* [x] `BlockedUserList`에 값 추가 시, 중복 검사 진행
