### ISSUE TITLE
[Fix] 신고, 차단 로직의 toggle 호출을 정리합니다.

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#416]
### 📝 작업 목적

GitSpace의 신고 및 차단 기능에서 sheet를 불러오는 로직의 toggle 호출을 점검합니다.

---

### 🛠️ Tasks

* [x] 신고
  * [x] 신고 기능에서 sheet를 불러오는 로직 확인
  * [x] SuggestBlockView, ReportView와 연결된 toggle 호출 확인
* [x] 차단
  * [x] 차단 기능에서 sheet를 불러오는 로직 확인
  * [x] BlockView와 연결된 toggle 호출 확인
