### ISSUE TITLE
[Fix] 신고/차단 Sheet 작동 방식을 수정합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#417]
### 📝 작업 목적

1. 현재 신고 -> 차단 제안 -> 차단으로 이어지는 sheet를 사용하려면 호출하는 View에서 3개의 halfSheet를 사용해서 작동해야하는 번거로움이 있습니다. 연속되는 sheet를 하나의 View로 통합하여 신고 sheet 사용성을 증가시킵니다.
2. 현재 1번의 연속 sheet를 사용할 때, 상대방 차단 여부를 검사하지 않고 SuggestView가 작동하고 있습니다. 이미 상대방을 차단한 상태라면 차단을 제안하지 않는 것이 자연스러운 UX이므로 차단 여부 검사 로직을 추가합니다.

---

### 🛠️ Tasks

* [ ] 신고/제안/차단 sheet를 통합한 View 구현
* [ ] 기존 halfSheet 사용 코드를 구현한 View로 변경
* [ ] SuggestView present 여부를 결정하기 위한 차단 여부 검사 로직 구현
