### ISSUE TITLE
[Fix] GSTextEditor 구현부 로직을 정리합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#421]
### 📝 작업 목적
- 현재 GSTextEditor는 동적 높이 계산을 위해 다양한 연산 프로퍼티와 메서드가 구현되어있습니다.
- 중복되는 코드와 불필요한 연산 프로퍼티가 발견되어 이를 정리합니다.

---

### 🛠️ Tasks

* [x] 최초 1회만 계산이 필요한 프로퍼티를 연산 프로퍼티에서 저장 프로퍼티로 변경하고 이니셜라이저에서 계산하도록 변경
* [x] Int <-> CGFloat 타입의 변환 가독성을 높이기 위한 extension 추가
* [x] 메서드 스코프 내에서 반복적으로 사용되는 값을 프로퍼티로 분리하여 참조할 수 있도록 수정
