### ISSUE TITLE
[Fix] GitSpaceUser 확인 로직을 변경합니다.

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#422]
### 📝 작업 목적

GitSpaceUser 확인 로직을 firestore db를 조회하여 쿼리실행 후 검증하는 방법으로 변경합니다.

---

### 🛠️ Tasks

* [x] 기존 GitSpace 유저 확인 로직을 사용하는 파일 파악 및 점검
  * [x] ContributorListCell
    * [x] contributor목록을 확인하여 해당 contributor의 github ID로 UserInfo를 요청하고, 해당 UserInfo가 있다면(nil이 아니라면) list에 id를 넣어 관리 -> githubID로 UserInfo를 요청하는 부분에서 firestore db를 조회하여 쿼리실행 후 UserInfo? 타입으로 리턴
  * [x] TargetUserProfileView
* [x] GitSpace 유저 확인 로직 변경
  * [x] Firestore Collection에 접근 후 document 검색 쿼리 실행
  * [x] 위 결과를 UserInfo 타입으로 캐스팅하여 githubID를 비교
* [x] GitSpace 유저 확인 로직이 사용되는 곳에 변경사항 일괄 적용
