### ISSUE TITLE
[Fix] View Profile → Chat/Knock View → View Profile의 무한 라우팅을 해결합니다.

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#424]
### 📝 작업 목적
`View Profile` → `Chat/Knock View` → `View Profile`의 무한 라우팅을 해결합니다.

### 무한 라우팅이 발생하는 시나리오
1. `Chat View` → `View Profile` 버튼 → `Knock` 버튼
2. `Received Knock View` → `View Profile` 버튼 → `Knock` 버튼
3. `Send Knock View` → `View Profile` 버튼 → `Knock` 버튼

---

### 🛠️ Tasks

* [ ] 무한 라우팅이 발생하는 원인 파악
* [ ] 해당 원인에 대한 해결 방안 모색
* [ ] 무한 라우팅 해결
