### ISSUE TITLE
[Feat] User Listener를 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#426]
### 📝 작업 목적
차단 기능이 추가되면서 차단 액션 후 `User`의 차단 목록 업데이트가 필요합니다.

Firestore DB에는 업데이트가 반영되지만, 로컬 `User` 데이터에도 반영이 필요한데, 차단 기능이 `Blockable` 프로토콜에 의존하는 구조로 되어있습니다.

프로토콜 내부에서는 `EnvironmentObject` 사용이 불가해서 앱 전반에서 사용하는 `UserViewModel`에 접근할 수 없기 때문에 차단 기능을 사용하는 모든 View에서 `UserViewModel`을 의존하고 직접 `User` Request 호출까지 별도로 해야하는 상황입니다.

이를 해결하기 위해 Firestore DB의 `User`가 업데이트 될 때, 이를 감지하여 로직을 수행할 수 있는 `Listener`를 구현합니다.

---

### 🛠️ Tasks

* [x] User Listener 추가
* [x] User Modified 감지 시, 변경된 문서를 currentUser에 업데이트하는 로직 구현
* [x] InitialView에 로그인 유저에 대한 Listener를 추가하여 전역적으로 작동하도록 추가
