### ISSUE TITLE
[Fix] UserViewModel의 User와 currentUser를 통합합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#427]
### 📝 작업 목적
현재 UserViewModel의 user와 currentUser는 같은 기능과 용도로 사용되고 있습니다.

두 프로퍼티가 여러 로직에서 따로 사용되고 있어서 하나의 프로퍼티로 통합합니다.

---

### 🛠️ Tasks

* [x] user 프로퍼티 삭제
* [x] user, currentUser 관련 함수 및 로직을 하나로 통합
* [x] user를 호출하고 있는 로직을 currentUser로 변경
