### ISSUE TITLE
[Feat] HomeView > Following(Activity)

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#44]
### 📝 작업 목적

HomeView의 
Following View (Activity View)를 기획한 디자인에 맞춰 구현합니다.

---

### 🛠️ Tasks

* [x] Figma 확인 후 기존 코드 수정 및 확인
* [x] 작업하면서 모델링 할 부분 체크
* [x] 서브뷰를 나누면서 디자인 시스템을 적용할 컴포넌트 정리
* [x] 다크모드 대응
* [x] 임시 이미지 적용
