### ISSUE TITLE
[Fix] 채팅 메세지 필드가 포커스되어 키보드가 올라올 때, 채팅 메세지 ScrollView 영역이 키보드에 맞춰서 올라가지 않는 현상을 수정합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#441]
### 📝 작업 목적
- 현재 ChatRoomView의 TextEditor가 포커스되어 키보드가 올라올 때, 채팅 메세지 ScorllView 영역이 키보드에 맞춰서 올라오지 않는 현상이 있음

### 예상 해결 방법
- Keyboard가 나타나는 것을 감지하는 Publisher에서 keyboardHeight를 계산
- keyboard가 showing했을 때, ScrollView bottom padding에 keyboardHeight를 전달해서 컨텐츠 영역 줄이기

---

### 🛠️ Tasks

* [ ] 키보드 감지 Publisher 확인
* [ ] keyboardHeight 계산 로직 추가
* [ ] ScrollView bottom padding 추가
