### ISSUE TITLE
[Feat] GitSpace 문자열 약식 암호화 로직을 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#442]
### 📝 작업 목적
현재 DB에서는 노크 / 채팅 메세지를 별도의 변환 없이 업데이트 하고 있습니다. 사용자의 사생활 보호 및 개인정보보호 처리방침 준수를 위한 암호화 로직을 구현합니다.

---

### 🛠️ Tasks

* [ ] 대칭키 추가
* [ ] Xcconfig 저장 구현
* [ ] 암호화 / 복호화 로직 구현
* [ ] 서버 읽기 / 쓰기 테스트
