### ISSUE TITLE
[Feat] Knock Contents > Encryption

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#443]
### 📝 작업 목적

- #442 
- Knock Message Encryption
---

### 🛠️ Tasks

* [x] Knock Message Encryption
    * [x] read > Running Map method on Temp Array
    * [x] create > Knock.knockMessage assign a encoded String
