### ISSUE TITLE
[Feat] Tag에 약식 암호화를 적용합니다.

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#445]
### 📝 작업 목적

- #442 
- 사용자 지정 Tag 저장에 약식 암호화를 적용합니다.
- GitSpace 암호화는 약식 암호화를 우선 적용 후, CryptoKit으로 바꿀 예정입니다.

---

### 🛠️ Tasks

* [x] 사용자 지정 Tag를 추가할 때, base64 인코딩
* [x] 사용자 지정 Tag를 불러올 때, base64 디코딩
* [x] 이미 만들어진 String extension의 base64 인/디코딩 메서드 사용하기
