### ISSUE TITLE
[Feat] Encryption DB Update

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#449]
### 📝 작업 목적

1. 서버의 모든 Raw 데이터를 불러온 후 암호화하여 Update 하는 Script를 구현합니다.
2. 업데이트 유무 확인 및 강제 업데이트 분기처리 하는 코드를 구현하여 버전 업데이트 배포를 준비합니다.

---

### 🛠️ Tasks

* [x] #450
* [x] #451 
* [x] (Debug 서버) Raw Data Encryption
* [x] (Debug 서버) Encoded Data Upload
* [x] App Version Available Check
* [x] App Version Force Update

**Comment by ValseLee** [comment]
"이건 절대 `main`으로 올려선 안 돼!"
작업용 브랜치에서 앱 심사 끝나는 시점에 DB 암호화 하기
