### ISSUE TITLE
[Feat] HomeView > Starred

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#45]
### 📝 작업 목적
메인 홈뷰의 Starred 뷰를 피그마 디자인대로 구현합니다. 
 
---

### 🛠️ Tasks

* [x] 기존 코드 훑어보기
* [x] 피그마 디자인에 맞게 디자인 요소 수정하기
    * [x] MainHomeView > Tab Button
    * [x] StarredView > SelectedTag
    * [x] StarredView > RepoCardView
    * [x] StarredView Background Gradation
* [x] 다크모드 대응 (텍스트 컬러, 카드뷰 배경 컬러, 아이콘 색상)
* [x] AddTagSheetView 연결하기
* [x] AddTagSheetView 피그마 디자인에 맞게 디자인 요소 수정하기

#51
