### ISSUE TITLE
[Feat] Firebase FireStore에 저장된 데이터에 암호화를 적용하는 스크립트를 작성합니다.

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#450]
### 📝 작업 목적

Firebase의 모든 Raw 데이터를 불러온 후 암호화하여 Update하는 Script를 작성합니다.
---

### 🛠️ Tasks

* [x] 암호화가 적용될 Document 파악하기
* [x] (Debug 서버) 암호화 적용
* [x] (Debug 서버) 암호화가 적용된 데이터를 Firebase에 업데이트
