### ISSUE TITLE
[Feat] 앱 버전 체크 및 강제 업데이트 로직을 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [APPSCHOOL1-REPO/finalproject-gitspace#451]
### 📝 작업 목적
- #449 
- 이번 메세지 암호화 작업으로 다음 클라이언트를 업데이트 하지 않은 유저는 정상적으로 채팅을 확인할 수 없는 이슈가 발생할 예정
- 수동으로 업데이트 하지 않는 유저를 위해 강제 업데이트 로직을 구현한 앱 버전을 우선적으로 배포하여 사이드 이펙트를 방지하기 위함

---

### 🛠️ Tasks

* [x] ITunes API를 통해 최신 앱 버전을 확인하는 로직 구현
* [x] 클라이언트 앱 버전을 체크해서 최신 앱 버전과 비교하는 로직 구현
* [x] 강제 업데이트 리다이렉팅 알럿 구현
