### ISSUE TITLE
[Feat] ChatView > NewKnockView

### ISSUE THREAD

**Issue by guguhanogu** [APPSCHOOL1-REPO/finalproject-gitspace#47]
### 📝 작업 목적
노크박스 뷰에서 새로운 노크 메세지를 보낼 때의 화면을 구현합니다.
1. 새로운 노크 메세지 보내기 버튼을 누릅니다.
2. 새로운 노크 메세지를 받을 사람을 검색합니다.
3. 채팅의 목적을 선택합니다. (Offer / Question)
4. 노크 메세지를 입력하고 전송합니다. 
---

### 🛠️ Tasks

* [x] 수신자 입장: 노크 메세지
   * [x] 발신자 프로필 뷰 구현
   * [x] 수신받은 노크 메세지 뷰 구현
   * [x] 노크에 대한 응답 선택 뷰 구현
  
* [x] ~~발신자 입장: 받을 사람 검색 뷰~~

* [x] 발신자 입장: 노크 메세지 전송 뷰
   * [x] 수신자 프로필 뷰 구현 
   * [x] 노크 목적 버튼 구현
   * [x] 노크 목적 버튼 누를 시 스크롤 이동 구현
   * [x] 노크 목적 버튼 누를 시 안내 문구 및 예시 노크 메세지 뷰 구현
   * [x] 텍스트 에디터 구현
