### ISSUE TITLE
[Feat] Prototype MainHomeView > Following View

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#5]
### 📝 작업 목적

프로토타입 홈뷰의 Following View를 구현합니다.

---

### 🛠️ Tasks

* [x] 전체 Following View 구성
  * [x] 각 Feed View 제작
    * [x] Context Menu 추가 
  * [x] Feed View의 Profile(Circle Image)을 눌렀을때 Repository Detail View로 이동하도록 연결
  * [x] Feed View의 Repository Text를 눌렀을때 Profile Detail View로 이동하도록 연결
