### ISSUE TITLE
[Fix] 태그가 중복해서 선택되는 문제

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#58]
### 📝 작업 목적
AddTagView에서 태그가 중복해서 선택되는 문제를 해결합니다.

---

### 🛠️ Tasks

* [x] Done을 누르면 태그가 최종적으로 선택되도록 하기
* [x] 태그가 중복되서 올라가는 문제 해결
* [x] Tag버튼을 디자인 시스템 버튼으로 변경
* [x] 디자인시스템 버튼에 맞게 태그 선택 로직 변경
* [x] 새로운 태그를 추가하면 뷰에 바로 나타나도록 Published 설정
