### ISSUE TITLE
[Fix] 사용자 추천 카드 UI 수정

### ISSUE THREAD

**Issue by lianne-b** [APPSCHOOL1-REPO/finalproject-gitspace#60]
### 📝 작업 목적

- ChatRecommandCardSection이 배경과 구분될 수 있도록 수정합니다.

---

### 🛠️ Tasks

* [x] 카드 부분 그림자 값 변경
* [x] 카드 UI 디테일 수정
* [x] navlink로 노크 버튼을 newknockView에 연결
