### ISSUE TITLE
[Feat] RepositoryDetailView

### ISSUE THREAD

**Issue by jekyun-park** [APPSCHOOL1-REPO/finalproject-gitspace#61]
### 📝 작업 목적

목요일 UX피드백에 앞서 기획한 피그마 디자인에 따라 완성이 되지 않은 뷰를 작업합니다.

---

### 🛠️ Tasks

* [x] 피그마 디자인 및 기존 코드 확인
* [x] 추후 모델링이 필요한 부분 문서로 작성
* [x] 서브뷰를 나누고, 디자인 시스템이 적용될 컴포넌트 정리
* [x] 다크모드 대응
* [x] 임시 이미지 적용
