### ISSUE TITLE
[Fix] ContributorListView 뷰 수정

### ISSUE THREAD

**Issue by lianne-b** [APPSCHOOL1-REPO/finalproject-gitspace#62]
### 📝 작업 목적

기존 와이어프레임 화면을 프로토타입 단계 UI로 수정합니다. 

---

### 🛠️ Tasks

* [x] 전반적인 UI 개선 및 노크 뷰 연결
* [x] 기존 List > 커스텀이 용이한 일반 텍스트 컴포넌트로 변경 
* [x] contentShape으로 카드 전체 선택 가능하게 수정
