### ISSUE TITLE
[Fix] ChatView > ChatListSection 리스트 cell 레이아웃 수정 및 추가 기능 구현

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#64]
### 📝 작업 목적
- 피드백 후 소소한 수정과 함께 이전 과정에서 마저 구현하지 못했던 특징들을 구현. (ListSection에서 리스너 연결 및 깃헙 API 연결)
---

### 🛠️ Tasks

* [ ] [기능구현] 깃헙 API를 통해 채팅하는 상대 프로필 사진 호출해서 뷰에 보여주기.
* [x] [기능구현] ListSection에서의 리스너 활성화. List를 보고있을 때도 메시지가 오면 화면이 바로바로 반영이 되어야 한다.
* [x] [뷰 수정] 각 List Cell의 frame 크기 수정.
* [x] [후순위작업] ListSection 접속 시 List 뜨는 속도가 느림. 최적화 필요. (이미지, 이름, 내용 뜨는 순서도 다 제각각인 것 수정 필요)
