### ISSUE TITLE
[Feat] Prototype MainPenpalView > PenpalListView

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#7]
### 📝 작업 목적

- 펜팔 리스트 뷰와 펜팔 노크 모달 뷰를 프로토타입 수준으로 구현합니다.

---

### 🛠️ Tasks

* [x] 펜팔 리스트 뷰 구현
* [x] 펜팔 노크 모달 뷰 구현
* [x] 펜팔 리스트 뷰의 버튼으로 펜팔 노크 모달을 트리거
