### ISSUE TITLE
[Feat] Text 디자인시스템 구현 + Constant에 Text 속성값 정리

### ISSUE THREAD

**Issue by yeseul321** [APPSCHOOL1-REPO/finalproject-gitspace#85]
### 📝 작업 목적
Text 관련 디자인시스템 구현
---

### 🛠️ Tasks

* [x] Constant 파일에 GSTextConst enum 생성 및 각 text 디자인에 필요한 속성값 정리.
* [x] Component 폴더 하위에 GSText 파일 생성하여 Text 디자인시스템 구현
    * [x] Title 종류 (Title1, Title2, Title3, Section Title)
    * [x]  Body 종류 (Body1, Body2)
    * [x]  그 외 (Caption1, Caption2, Description)
