### ISSUE TITLE
[Feat] Design System: TextEditor

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#90]
### 📝 작업 목적

GitSpace의 Chat, Knock 뷰에서 사용되는 GSTextEditor를 구현합니다.

---

### 🛠️ Tasks

* [x] TextEditor 멀티라인 구현 가능한지 확인
* [x] TextEditor 관련 Constant 세팅
* [x] TextEditor 동적 멀티라인 로직 구현
* [x] TextEditor 추상화 (Design System)
* [x] TextEditor 인스턴스 작동 테스트

### Contributors
@wontaeyoung 
@dahae0320 
@guguhanogu
