### ISSUE TITLE
[Fix] Tag Action(태그 중복 저장, 화면 스크롤)

### ISSUE THREAD

**Issue by dahae0320** [APPSCHOOL1-REPO/finalproject-gitspace#95]
### 📝 작업 목적

AddTagSheetView사용되는 태그 액션 기능을 수정합니다. (태그 중복 저장, 화면 스크롤)

---

### 🛠️ Tasks

* [x] AddTagSheetView에서 tag 중복 저장 막기
* [x] AddTagSheetView에서 스크롤이 가능하도록 수정
* [x] AddTagSheetView에서 최신 태그가 가장 앞에 오도록 수정
* [x] StarredView에서 태그 삭제 transition
* [x] AddTagSheetView에 FlowLayout 설정
* [x] 꾹 눌러서 태그 삭제하기
* [x] 디테일뷰에서 태깅 시나리오 및 태그 모델 구상
