### ISSUE TITLE
[Fix] MainKnockView > 라벨링 수정 및 노크 상태를 반영하는 뷰 수정

### ISSUE THREAD

**Issue by ValseLee** [APPSCHOOL1-REPO/finalproject-gitspace#97]
### 📝 작업 목적

- 유저 피드백을 반영하여 변경사항을 구현합니다.

---

### 🛠️ Tasks

* [x] sended → sent 로 레이블 변경 필요
* [x] MainKnockView 에서 시간과 상태순으로 정렬
* [x] Knock 상태를 보여주는 화면 변경
    * [x] 채팅버튼 상단으로 옮기기
    * [x] 상태 필터링 관련 레이블 추가
* [x] Knock 검색 뷰 구현
* [x] Knock 탭을 가로 스크롤로 이동 못하도록 제한
